name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # You can update the version if needed

    - name: Install dependencies
      run: npm install

    # Skipping the npm test step for now
    # - name: Run tests
    #   run: npm test

    - name: Lint code
      run: npm run lint  # You can remove this step if you don't have a linter set up

    - name: Deploy to server (optional, if you have deployment steps)
      run: |
        echo "Add deployment commands here"  # Replace with your deployment steps, if any
